web:
  build: ./web
  ports:
    - "3000:3000"
  volumes:
    - ./code/web:/srv/www/
  command: bash -c "cd /srv/www && npm install && node /srv/www/server.js"
  links:
    - api
    - redis
    - mongodb
    - elasticsearch

api:
  build: ./api
  ports:
    - "3030:3030"
  volumes:
    - ./code/api:/srv/www/
  command: bash -c "cd /srv/www && npm install && node /srv/www/server.js"

redis:
  image: redis

mongodb:
  image: bitnami/mongodb:latest
  ports:
    - "27017:27017"
  environment:
    - MONGODB_USERNAME=my_user
    - MONGODB_PASSWORD=password123
    - MONGODB_DATABASE=my_database

elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
